# Generated by Django 4.2 on 2023-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('payee', models.CharField(max_length=240, verbose_name='Payee')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('budget_category', models.CharField(max_length=240, verbose_name='Budget_Category')),
            ],
        ),
    ]
