# Generated by Django 4.2 on 2023-04-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_records', '0001_initial'),
    ]

    operations = [
    ]
