# Generated by Django 4.2 on 2023-04-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=240, verbose_name='FirstName')),
                ('last_name', models.CharField(default='', max_length=240, verbose_name='LastName')),
                ('apartment_number', models.IntegerField(default=0, verbose_name='apartmentNumber')),
            ],
        ),
    ]
