# Generated by Django 4.2 on 2023-04-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_apartment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='apartment_number',
        ),
    ]
