# Generated by Django 4.2 on 2023-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_apartment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='apartment_number',
            field=models.IntegerField(default=0, verbose_name='ApartmentNumber'),
        ),
    ]
