# Generated by Django 4.2 on 2023-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_email_tenant_lease_start_tenant_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default='', max_length=240, verbose_name='Email'),
        ),
    ]
