# Generated by Django 4.2 on 2023-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.CharField(default='', max_length=240, verbose_name='Email'),
        ),
    ]
