# Generated by Django 4.2 on 2023-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240, verbose_name='username')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
            ],
        ),
    ]
