# Generated by Django 4.2 on 2023-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(default='', max_length=240, verbose_name='FirstName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(default='', max_length=240, verbose_name='LastNName'),
            preserve_default=False,
        ),
    ]
