# Generated by Django 4.2 on 2023-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_first_name_tenant_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(default='', max_length=240, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(default='', max_length=240, verbose_name='LastNName'),
        ),
    ]
