# Generated by Django 4.2 on 2023-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_Income_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.IntegerField(verbose_name='Apartment_Number')),
                ('january', models.FloatField(verbose_name='January')),
                ('february', models.FloatField(verbose_name='February')),
                ('march', models.FloatField(verbose_name='March')),
                ('april', models.FloatField(verbose_name='April')),
                ('may', models.FloatField(verbose_name='May')),
                ('june', models.FloatField(verbose_name='June')),
                ('july', models.FloatField(verbose_name='July')),
                ('august', models.FloatField(verbose_name='August')),
                ('september', models.FloatField(verbose_name='September')),
                ('october', models.FloatField(verbose_name='October')),
                ('november', models.FloatField(verbose_name='November')),
                ('december', models.FloatField(verbose_name='December')),
            ],
        ),
    ]
