# Generated by Django 4.2 on 2023-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_income_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalincomerecord',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Total'),
        ),
    ]
